<?php

namespace Database\Seeders;

use App\Models\Destination;
use Illuminate\Database\Seeder;

class DestinationSeeder extends Seeder
{
    public function run(): void
    {
        $img = fn (string $name) => "/images/dharamshala/{$name}.jpg";

        $destinations = [
            [
                'name'        => 'McLeodganj',
                'slug'        => 'mcleodganj',
                'category'    => 'Hill Town',
                'tagline'     => 'Little Lhasa of the Himalayas',
                'short_desc'  => 'The hilltop home of the Tibetan government-in-exile, packed with monasteries, cafés, momo stalls and bustling bazaars under the Dhauladhar peaks.',
                'description' => "McLeodganj sits on a ridge above Dharamshala and is the heart of the Tibetan community in India. Since 1960 it has been home to His Holiness the Dalai Lama and the Central Tibetan Administration, which is why it is often called \"Little Lhasa\".\n\nThe town is small enough to explore on foot: the Temple Road and Jogiwara Road bazaars are lined with Tibetan handicrafts, prayer flags, bookshops and cafés serving thukpa, momos and butter tea. Most visitors base themselves here to explore Bhagsu, Dharamkot, Naddi and the Triund trek.\n\nRoads in McLeodganj are narrow and parking is limited, so a local driver who knows the one-way loops makes arrivals and departures much easier.",
                'image'       => $img('mcleodganj-market'),
                'gallery'     => [$img('mcleodganj-market'), $img('mcleodganj-view'), $img('prayer-flags')],
                'highlights'  => ['Tsuglagkhang Complex & Namgyal Monastery', 'Tibetan market on Temple Road', 'Cafés with Dhauladhar views', 'Base for Triund, Bhagsu & Dharamkot'],
                'distance'    => '9 km from Dharamshala • 22 km from Gaggal Airport',
                'altitude'    => 'approx. 2,080 m',
                'best_time'   => 'March to June, September to December',
                'timings'     => 'Open all day',
                'entry_fee'   => 'Free',
                'how_to_reach'=> 'Around 25–30 minutes by taxi from Dharamshala and 45–60 minutes from Gaggal Airport (DHM). The nearest broad-gauge railway station is Pathankot, about 90 km away.',
                'latitude'    => 32.2426,
                'longitude'   => 76.3213,
                'is_featured' => true,
            ],
            [
                'name'        => 'Tsuglagkhang Complex (Dalai Lama Temple)',
                'slug'        => 'dalai-lama-temple-tsuglagkhang',
                'category'    => 'Monastery',
                'tagline'     => 'The spiritual centre of McLeodganj',
                'short_desc'  => 'The main temple of the Tibetan community in exile, with the Namgyal Monastery, the Tibet Museum and the residence of His Holiness the Dalai Lama.',
                'description' => "The Tsuglagkhang Complex is the most important Tibetan Buddhist site in India. It houses the main temple with statues of Shakyamuni Buddha, Avalokiteshvara and Padmasambhava, the Namgyal Monastery — the personal monastery of the Dalai Lama — and the Tibet Museum, which tells the story of Tibet's history and exile.\n\nVisitors can join the kora, a peaceful circumambulation path lined with prayer wheels and prayer flags that loops around the complex through the forest. Early mornings and evenings are the best times to watch monks debating in the courtyard.\n\nPhotography is restricted inside the main prayer halls, and modest clothing is appreciated.",
                'image'       => $img('namgyal-temple'),
                'gallery'     => [$img('namgyal-temple'), $img('tsuglagkhang'), $img('mcleodganj-view')],
                'highlights'  => ['Namgyal Monastery', 'Tibet Museum', 'Kora walk with prayer wheels', 'Monks debating in the courtyard'],
                'distance'    => 'In McLeodganj, 9 km from Dharamshala',
                'altitude'    => 'approx. 1,750 m',
                'best_time'   => 'All year; early morning for prayers',
                'timings'     => 'Approx. 5:00 AM – 8:00 PM (shorter hours in winter)',
                'entry_fee'   => 'Free',
                'how_to_reach'=> 'A short walk down Temple Road from McLeodganj main square. Taxis can drop you near the temple gate.',
                'latitude'    => 32.2327,
                'longitude'   => 76.3241,
                'is_featured' => true,
            ],
            [
                'name'        => 'Bhagsu Waterfall & Bhagsunag Temple',
                'slug'        => 'bhagsu-waterfall-bhagsunag-temple',
                'category'    => 'Nature',
                'tagline'     => 'An ancient Shiva temple and a mountain waterfall',
                'short_desc'  => 'A short drive from McLeodganj, the ancient Bhagsunag Shiva temple and its spring-fed pools lead to a gushing waterfall in a rocky gorge.',
                'description' => "Bhagsunag Temple is one of the oldest temples in the area, dedicated to Lord Shiva and known for its sacred spring-fed bathing pools. From the temple, a paved path of roughly a kilometre climbs to Bhagsu Waterfall, which is at its most powerful during and just after the monsoon.\n\nThe village of Bhagsu has grown into a lively stop with cafés, yoga schools and guesthouses. Continue up the trail to the Shiva Café above the falls for views across the valley.\n\nThe rocks near the falls can be slippery — wear good shoes, especially in the rainy season.",
                'image'       => $img('bhagsu-falls'),
                'gallery'     => [$img('bhagsu-falls'), $img('bhagsu-nag')],
                'highlights'  => ['Bhagsunag Shiva Temple', 'Sacred spring pools', 'Bhagsu Waterfall', 'Shiva Café above the falls'],
                'distance'    => '2 km from McLeodganj • 11 km from Dharamshala',
                'altitude'    => 'approx. 1,800 m',
                'best_time'   => 'March to June, and July to September for full flow',
                'timings'     => 'Temple approx. 6:00 AM – 9:00 PM',
                'entry_fee'   => 'Free',
                'how_to_reach'=> 'A 10-minute drive or 30-minute walk from McLeodganj. Cabs drop at the Bhagsunag Temple parking.',
                'latitude'    => 32.2441,
                'longitude'   => 76.3339,
                'is_featured' => true,
            ],
            [
                'name'        => 'Triund',
                'slug'        => 'triund-trek',
                'category'    => 'Trek',
                'tagline'     => 'The most popular day trek in Dharamshala',
                'short_desc'  => 'A grassy ridge at around 2,850 m with a front-row view of the Dhauladhar range on one side and the Kangra Valley on the other.',
                'description' => "Triund is the classic Dharamshala trek and suitable for most first-time trekkers. The trail starts at Gallu Devi temple above Dharamkot (or from McLeodganj) and climbs around 7 km through oak, deodar and rhododendron forest to the open ridge.\n\nAt the top, the Dhauladhar wall rises sharply ahead while the valley drops away below. Many trekkers camp overnight for the sunset and sunrise; others make it a long day trip. Experienced trekkers can continue to the Snowline and Laka Glacier.\n\nAvoid the trek during heavy snowfall or monsoon thunderstorms, carry water, and leave no litter on the ridge.",
                'image'       => $img('triund-ridge'),
                'gallery'     => [$img('triund-ridge'), $img('triund-hilltop'), $img('triund-campsite'), $img('five-towns-triund')],
                'highlights'  => ['Sunrise & sunset over the Dhauladhars', 'Overnight camping', 'Forest trail with rhododendrons', 'Extension to Snowline & Laka Glacier'],
                'distance'    => 'Trailhead 3 km from McLeodganj',
                'altitude'    => 'approx. 2,850 m',
                'best_time'   => 'March to June, September to December',
                'timings'     => 'Start the trek by 9:00 AM',
                'entry_fee'   => 'Nominal forest entry fee may apply',
                'how_to_reach'=> 'Take a cab to the Gallu Devi temple trailhead above Dharamkot to save about 2 km of uphill walking.',
                'latitude'    => 32.2618,
                'longitude'   => 76.3517,
                'is_featured' => true,
            ],
            [
                'name'        => 'HPCA Cricket Stadium',
                'slug'        => 'hpca-cricket-stadium',
                'category'    => 'Landmark',
                'tagline'     => 'One of the most scenic cricket grounds in the world',
                'short_desc'  => 'The Himachal Pradesh Cricket Association Stadium hosts international and IPL matches against a backdrop of snow-capped Dhauladhar peaks.',
                'description' => "Opened in 2003, the HPCA Stadium sits at around 1,450 m and is famous for the snowy Dhauladhar range rising directly behind the pavilion. It has hosted Test, ODI, T20 International and IPL matches.\n\nOn non-match days visitors can usually enter the stands and the gallery for photographs. The stadium is in lower Dharamshala, close to the Kotwali Bazar and the War Memorial, so it fits easily into a local sightseeing day.",
                'image'       => $img('hpca-stadium'),
                'gallery'     => [$img('hpca-stadium')],
                'highlights'  => ['Dhauladhar backdrop', 'International & IPL venue', 'Easy add-on to local sightseeing'],
                'distance'    => '1 km from Dharamshala Kotwali Bazar',
                'altitude'    => 'approx. 1,450 m',
                'best_time'   => 'All year; clear mornings for mountain views',
                'timings'     => 'Approx. 9:30 AM – 6:00 PM on non-match days',
                'entry_fee'   => 'Small visitor ticket on non-match days',
                'how_to_reach'=> 'Located in lower Dharamshala, 30 minutes from Gaggal Airport by taxi.',
                'latitude'    => 32.1975,
                'longitude'   => 76.3256,
                'is_featured' => true,
            ],
            [
                'name'        => 'Kangra Fort',
                'slug'        => 'kangra-fort',
                'category'    => 'Heritage',
                'tagline'     => 'One of the oldest forts in India',
                'short_desc'  => 'The ancient seat of the Katoch dynasty, perched above the confluence of the Banganga and Manjhi rivers near Kangra town.',
                'description' => "Kangra Fort is the largest fort in the Himalayas and among the oldest in India, long associated with the Katoch rulers of Kangra. Over the centuries it was contested by the Mughals, the Sikhs under Maharaja Ranjit Singh and finally the British, before a major earthquake in 1905 left much of it in ruins.\n\nWalk up through a series of grand gateways to temples inside the fort and the ramparts overlooking the river valleys. The Maharaja Sansar Chand Katoch Museum at the entrance displays artefacts and Kangra miniature paintings.\n\nThe fort is easily combined with Masroor rock-cut temples, Brajeshwari Devi temple in Kangra town, and Chamunda Devi on a heritage day trip.",
                'image'       => $img('kangra-fort'),
                'gallery'     => [$img('kangra-fort'), $img('kangra-fort-ruins')],
                'highlights'  => ['Ancient gateways & ramparts', 'Views over Banganga & Manjhi rivers', 'Katoch dynasty museum', 'Close to Brajeshwari Devi temple'],
                'distance'    => '20 km from Dharamshala • 12 km from Gaggal Airport',
                'altitude'    => 'approx. 730 m',
                'best_time'   => 'October to April',
                'timings'     => 'Approx. 9:00 AM – 6:00 PM',
                'entry_fee'   => 'Ticketed (managed by the Kangra royal family trust)',
                'how_to_reach'=> 'Around 45 minutes by taxi from Dharamshala via Kangra town.',
                'latitude'    => 32.0857,
                'longitude'   => 76.2614,
                'is_featured' => true,
            ],
            [
                'name'        => 'Dal Lake, Dharamshala',
                'slug'        => 'dal-lake-dharamshala',
                'category'    => 'Nature',
                'tagline'     => 'A quiet lake in the deodar forest',
                'short_desc'  => 'A small, peaceful mountain lake near Naddi surrounded by tall deodar trees, with a small Shiva temple on its banks.',
                'description' => "Not to be confused with the famous lake in Srinagar, Dharamshala's Dal Lake is a small lake near the village of Tota Rani, between McLeodganj and Naddi. It is ringed by deodar cedars and has a small Shiva temple on its bank.\n\nThe lake is a calm stop on the way to Naddi viewpoint, where the Dhauladhar range feels close enough to touch, especially at sunset. A local fair is held at the lake each year after the monsoon.",
                'image'       => $img('dal-lake'),
                'gallery'     => [$img('dal-lake'), $img('dhauladhar-peaks')],
                'highlights'  => ['Deodar forest setting', 'Small Shiva temple', 'Combine with Naddi sunset viewpoint'],
                'distance'    => '3 km from McLeodganj • 11 km from Dharamshala',
                'altitude'    => 'approx. 1,775 m',
                'best_time'   => 'March to June, September to November',
                'timings'     => 'Open all day',
                'entry_fee'   => 'Free',
                'how_to_reach'=> 'A 10-minute drive from McLeodganj on the Naddi road.',
                'latitude'    => 32.2453,
                'longitude'   => 76.3051,
                'is_featured' => false,
            ],
            [
                'name'        => 'St. John in the Wilderness',
                'slug'        => 'st-john-in-the-wilderness-church',
                'category'    => 'Heritage',
                'tagline'     => 'A neo-Gothic church in the deodar forest',
                'short_desc'  => 'A stone church built in 1852 at Forsyth Ganj, famous for its Belgian stained-glass windows and the memorial of Lord Elgin, a Viceroy of India.',
                'description' => "Set among deodar trees on the road between Dharamshala and McLeodganj, the Church of St. John in the Wilderness was built in 1852 and is one of the finest colonial buildings in Himachal. It survived the 1905 Kangra earthquake, although its bell tower was destroyed; the original bell now stands in the churchyard.\n\nInside are beautiful stained-glass windows, and the churchyard holds the memorial of James Bruce, 8th Earl of Elgin and Viceroy of India, who died in Dharamshala in 1863.",
                'image'       => $img('st-john-church'),
                'gallery'     => [$img('st-john-church')],
                'highlights'  => ['1852 neo-Gothic architecture', 'Belgian stained-glass windows', 'Memorial of Lord Elgin', 'Peaceful deodar forest'],
                'distance'    => '2 km before McLeodganj • 8 km from Dharamshala',
                'altitude'    => 'approx. 1,900 m',
                'best_time'   => 'All year',
                'timings'     => 'Approx. 10:00 AM – 5:00 PM; Sunday service in the morning',
                'entry_fee'   => 'Free',
                'how_to_reach'=> 'On the Forsyth Ganj road to McLeodganj — an easy stop on any local sightseeing tour.',
                'latitude'    => 32.2371,
                'longitude'   => 76.3184,
                'is_featured' => true,
            ],
            [
                'name'        => 'Norbulingka Institute',
                'slug'        => 'norbulingka-institute',
                'category'    => 'Monastery',
                'tagline'     => 'Living Tibetan art and craft',
                'short_desc'  => 'A tranquil institute dedicated to preserving Tibetan art, with Japanese-inspired gardens, artisan workshops and the Seat of Happiness temple.',
                'description' => "Norbulingka Institute in Sidhpur was founded to preserve Tibetan culture in its literary and artistic forms. Visitors can watch artisans at work on thangka painting, wood carving, metal statue making and appliqué in the workshops.\n\nThe gardens, with streams, bridges and maple trees, are one of the most peaceful places in the Kangra Valley. The Seat of Happiness (Deden Tsuglagkhang) temple houses a large gilded Buddha statue, and there is a small doll museum, café and shop on site.",
                'image'       => $img('norbulingka'),
                'gallery'     => [$img('norbulingka')],
                'highlights'  => ['Thangka painting workshops', 'Japanese-inspired gardens', 'Seat of Happiness temple', 'Doll museum & café'],
                'distance'    => '7 km from Dharamshala',
                'altitude'    => 'approx. 1,300 m',
                'best_time'   => 'All year',
                'timings'     => 'Approx. 9:00 AM – 5:30 PM',
                'entry_fee'   => 'Small entry ticket',
                'how_to_reach'=> 'A 20-minute drive from Dharamshala towards Sidhpur; pair it with Gyuto Monastery and Chamunda Devi.',
                'latitude'    => 32.1985,
                'longitude'   => 76.3570,
                'is_featured' => true,
            ],
            [
                'name'        => 'Dharamkot',
                'slug'        => 'dharamkot',
                'category'    => 'Hill Village',
                'tagline'     => 'Cafés, meditation and forest walks',
                'short_desc'  => 'A laid-back village above McLeodganj known for meditation centres, cosy cafés and the trailhead for the Triund trek.',
                'description' => "Dharamkot is a quiet village perched above McLeodganj and Bhagsu, with views over the Kangra Valley. It is home to the Tushita Meditation Centre and the Dhamma Sikhara Vipassana centre, and attracts long-stay travellers with its yoga schools, guesthouses and cafés.\n\nThe Gallu Devi temple just above the village is the most common starting point for the Triund trek. Lanes in Dharamkot are steep and narrow, so cabs usually drop visitors at the main road.",
                'image'       => $img('dharamkot'),
                'gallery'     => [$img('dharamkot'), $img('five-towns-triund')],
                'highlights'  => ['Tushita & Vipassana meditation centres', 'Cafés & guesthouses', 'Gallu Devi trailhead for Triund'],
                'distance'    => '3 km from McLeodganj',
                'altitude'    => 'approx. 2,100 m',
                'best_time'   => 'March to June, September to December',
                'timings'     => 'Open all day',
                'entry_fee'   => 'Free',
                'how_to_reach'=> 'A 15-minute drive from McLeodganj up the Dharamkot road.',
                'latitude'    => 32.2502,
                'longitude'   => 76.3297,
                'is_featured' => false,
            ],
            [
                'name'        => 'Gyuto Monastery',
                'slug'        => 'gyuto-monastery',
                'category'    => 'Monastery',
                'tagline'     => 'Tantric monastery with a mountain view',
                'short_desc'  => 'The Gyuto Tantric University in Sidhbari, framed by the Dhauladhar range and once the residence of the 17th Karmapa.',
                'description' => "Gyuto Monastery is one of the great Tibetan tantric colleges, re-established in India after 1959 and now based at Sidhbari below Dharamshala. Its golden-roofed main hall stands against a dramatic backdrop of the Dhauladhar peaks.\n\nThe monastery was the residence of the 17th Karmapa for many years. Visitors are welcome in the main prayer hall, which holds a large statue of the Buddha; please keep voices low during prayers.",
                'image'       => $img('gyuto-monastery'),
                'gallery'     => [$img('gyuto-monastery')],
                'highlights'  => ['Golden-roofed prayer hall', 'Dhauladhar backdrop', 'Close to Norbulingka'],
                'distance'    => '8 km from Dharamshala',
                'altitude'    => 'approx. 1,250 m',
                'best_time'   => 'All year',
                'timings'     => 'Approx. 8:00 AM – 5:00 PM',
                'entry_fee'   => 'Free',
                'how_to_reach'=> 'A 20-minute drive from Dharamshala to Sidhbari.',
                'latitude'    => 32.2056,
                'longitude'   => 76.3741,
                'is_featured' => false,
            ],
            [
                'name'        => 'Chamunda Devi Temple',
                'slug'        => 'chamunda-devi-temple',
                'category'    => 'Temple',
                'tagline'     => 'A revered Shakti temple on the Baner river',
                'short_desc'  => 'One of the most visited temples in Kangra, dedicated to Goddess Chamunda and set on the banks of the Baner river with the Dhauladhars behind.',
                'description' => "The Chamunda Devi Temple is dedicated to a fierce form of Goddess Durga and is one of the most important pilgrimage sites in the Kangra Valley. The temple complex sits on the banks of the Baner river, with a cave-like Shiva shrine and bathing ghats.\n\nIt lies on the Dharamshala–Palampur road, so it is easy to include on the way to Palampur, Baijnath or Bir Billing.",
                'image'       => $img('chamunda-temple'),
                'gallery'     => [$img('chamunda-temple')],
                'highlights'  => ['Shakti peeth of the Kangra Valley', 'Baner river ghats', 'On the route to Palampur & Bir'],
                'distance'    => '15 km from Dharamshala',
                'altitude'    => 'approx. 1,000 m',
                'best_time'   => 'All year; Navratri festivals are especially lively',
                'timings'     => 'Approx. 6:00 AM – 9:00 PM',
                'entry_fee'   => 'Free',
                'how_to_reach'=> 'A 30-minute drive from Dharamshala on the Palampur road.',
                'latitude'    => 32.1530,
                'longitude'   => 76.3830,
                'is_featured' => false,
            ],
            [
                'name'        => 'Masroor Rock Cut Temples',
                'slug'        => 'masroor-rock-cut-temples',
                'category'    => 'Heritage',
                'tagline'     => 'The Ellora of the Himalayas',
                'short_desc'  => 'A rare group of 8th-century monolithic temples carved out of a single sandstone ridge, reflected in a sacred pool.',
                'description' => "The Masroor temples are a group of Nagara-style shrines carved from one piece of rock in the 8th century, a technique found in very few places in India. Often compared to the Kailasa temple at Ellora, the complex is protected by the Archaeological Survey of India.\n\nClimb the stairs to the rooftop for views of the Dhauladhars across the valley, and look for the reflection of the temples in the rectangular pool in front.",
                'image'       => $img('masroor-temple'),
                'gallery'     => [$img('masroor-temple')],
                'highlights'  => ['8th-century monolithic temples', 'ASI-protected site', 'Rooftop views', 'Reflection pool'],
                'distance'    => '45 km from Dharamshala',
                'altitude'    => 'approx. 800 m',
                'best_time'   => 'October to April',
                'timings'     => 'Sunrise to sunset',
                'entry_fee'   => 'Small ASI ticket',
                'how_to_reach'=> 'Around 1.5 hours by taxi from Dharamshala via Kangra and Nagrota Surian road.',
                'latitude'    => 32.0726,
                'longitude'   => 76.1361,
                'is_featured' => false,
            ],
            [
                'name'        => 'Dharamshala Tea Gardens',
                'slug'        => 'dharamshala-tea-gardens',
                'category'    => 'Nature',
                'tagline'     => 'Home of GI-tagged Kangra tea',
                'short_desc'  => 'Rolling green tea estates around Dharamshala and Palampur, producing the delicate Kangra tea against a backdrop of snowy peaks.',
                'description' => "Tea has been grown in the Kangra Valley since the mid-19th century, and Kangra tea received a Geographical Indication tag for its distinctive flavour. Estates around Dharamshala, Mann and Palampur produce both green and black teas.\n\nA walk through the neat rows of tea bushes with the Dhauladhar range behind is one of the most photogenic experiences in the valley. Some estates offer short factory visits and tastings during the plucking season.",
                'image'       => $img('dharamshala-tea-garden'),
                'gallery'     => [$img('dharamshala-tea-garden'), $img('kangra-tea-garden'), $img('palampur-tea')],
                'highlights'  => ['GI-tagged Kangra tea', 'Mountain-backed tea estates', 'Tastings in season'],
                'distance'    => '3–35 km from Dharamshala (Mann to Palampur)',
                'altitude'    => 'approx. 1,000–1,400 m',
                'best_time'   => 'March to May and September to November',
                'timings'     => 'Daylight hours',
                'entry_fee'   => 'Free to walk; tours may be charged',
                'how_to_reach'=> 'Estates line the Dharamshala–Palampur road; ask your driver to stop at a viewpoint.',
                'latitude'    => 32.1896,
                'longitude'   => 76.3470,
                'is_featured' => true,
            ],
            [
                'name'        => 'Bir Billing',
                'slug'        => 'bir-billing',
                'category'    => 'Adventure',
                'tagline'     => 'The paragliding capital of India',
                'short_desc'  => 'A world-class paragliding site where pilots launch from Billing (approx. 2,400 m) and land in the Tibetan village of Bir.',
                'description' => "Bir Billing hosted the Paragliding World Cup in 2015 and is considered one of the best paragliding sites in the world. Tandem flights take off from the Billing meadow and glide for 15–30 minutes over pine forests and tea gardens to the landing site at Bir.\n\nBeyond flying, Bir has a relaxed Tibetan colony with monasteries such as Sherab Ling and Chokling, cafés and short hikes. It makes an excellent day trip or overnight stop from Dharamshala.",
                'image'       => $img('bir-paragliding'),
                'gallery'     => [$img('bir-paragliding'), $img('palampur-tea')],
                'highlights'  => ['Tandem paragliding', 'Tibetan monasteries', 'Cafés & hikes', 'Paragliding World Cup venue'],
                'distance'    => '65 km from Dharamshala',
                'altitude'    => 'Take-off approx. 2,400 m, landing approx. 1,400 m',
                'best_time'   => 'October to November, March to May',
                'timings'     => 'Flights typically 9:00 AM – 3:00 PM, weather permitting',
                'entry_fee'   => 'Tandem flights charged by operators',
                'how_to_reach'=> 'Around 2 hours by taxi from Dharamshala via Palampur and Baijnath.',
                'latitude'    => 32.0480,
                'longitude'   => 76.7186,
                'is_featured' => true,
            ],
            [
                'name'        => 'Kareri Lake',
                'slug'        => 'kareri-lake',
                'category'    => 'Trek',
                'tagline'     => 'A glacial lake in the Dhauladhars',
                'short_desc'  => 'A shallow, freshwater glacial lake at around 2,934 m, reached by a beautiful trek along the Nyund stream from Kareri village.',
                'description' => "Kareri (Kumarwah) Lake is fed by snowmelt from the Minkiani Pass in the Dhauladhar range. The trek from Kareri village follows the Nyund stream through forest, meadows and Gaddi shepherd settlements, and is usually done over two to three days.\n\nA small temple dedicated to Lord Shiva and Goddess Shakti stands on a hill beside the lake. The lake is usually frozen from December to March.",
                'image'       => $img('kareri-lake'),
                'gallery'     => [$img('kareri-lake'), $img('dhauladhar-peaks')],
                'highlights'  => ['Glacial lake trek', 'Gaddi shepherd trails', 'Lakeside temple'],
                'distance'    => '30 km drive from Dharamshala to Kareri village',
                'altitude'    => 'approx. 2,934 m',
                'best_time'   => 'May to June, September to October',
                'timings'     => 'Start the trek early',
                'entry_fee'   => 'Free',
                'how_to_reach'=> 'Taxi to Kareri village (about 1.5 hours), then a 13 km trek.',
                'latitude'    => 32.3238,
                'longitude'   => 76.2635,
                'is_featured' => false,
            ],
            [
                'name'        => 'War Memorial, Dharamshala',
                'slug'        => 'war-memorial-dharamshala',
                'category'    => 'Landmark',
                'tagline'     => 'Tribute to the brave soldiers of Himachal',
                'short_desc'  => 'A serene memorial set in a pine forest at the entrance of Dharamshala, honouring soldiers from Himachal Pradesh who laid down their lives.',
                'description' => "The War Memorial stands among tall pine trees at the entrance to Dharamshala and commemorates the soldiers of Himachal Pradesh who sacrificed their lives defending the nation. Black marble panels bear the names of the fallen, and the landscaped grounds are well kept and peaceful.\n\nThe memorial is next to the Dharamshala cantonment area and just a few minutes from the HPCA Stadium, making it an easy first stop on a local tour.",
                'image'       => $img('war-memorial'),
                'gallery'     => [$img('war-memorial')],
                'highlights'  => ['Names of the fallen on marble panels', 'Pine forest park', 'Close to HPCA Stadium'],
                'distance'    => '1 km from Dharamshala town',
                'altitude'    => 'approx. 1,400 m',
                'best_time'   => 'All year',
                'timings'     => 'Approx. 9:00 AM – 7:00 PM',
                'entry_fee'   => 'Small entry ticket',
                'how_to_reach'=> 'At the entrance of Dharamshala town on the Kangra road.',
                'latitude'    => 32.2120,
                'longitude'   => 76.3236,
                'is_featured' => false,
            ],
        ];

        foreach ($destinations as $index => $destination) {
            Destination::updateOrCreate(
                ['slug' => $destination['slug']],
                $destination + [
                    'sort_order'       => $index,
                    'meta_title'       => "{$destination['name']} — Travel Guide, Timings & Taxi | Dharamshala Travels",
                    'meta_description' => $destination['short_desc'],
                ]
            );
        }
    }
}
